using UnityEditor;
using UnityEngine;
using Astra.Contracts;
using Astra.Core.Config;
using Astra.Drone;
using Astra.Flight;

namespace Astra.EditorTools
{
    /// <summary>
    /// Builds the UAV digital twin hierarchy procedurally.
    ///
    /// WHY A BUILDER RATHER THAN A PREFAB IN THE REPOSITORY
    /// ---------------------------------------------------
    /// A Unity prefab is a YAML document full of generated file IDs and GUID references. Hand-authoring
    /// one is possible and is a bad idea: a single wrong ID produces a prefab that either fails to load
    /// or loads with silently broken references, and the error message points at the asset rather than
    /// at the mistake. Building the hierarchy in code means the geometry, the component metadata and
    /// the wiring are all reviewable as source, they can be regenerated after any change to the
    /// airframe, and a mistake is a compile error rather than a corrupt asset.
    ///
    /// It also means the airframe is DOCUMENTED BY ITS CONSTRUCTOR. Every position below is derived
    /// from a dimension in UavConfiguration rather than typed in, so changing the wheelbase moves the
    /// motors and the arms follow. A prefab would let the visual model and the physics model drift
    /// apart, which is the specific failure that turns a digital twin back into an animation.
    ///
    /// GEOMETRY HONESTY
    /// ----------------
    /// The parts are built from Unity primitives. This is a functional engineering mock-up with
    /// correct placement, scale and articulation - not a CAD model and not a visually accurate replica
    /// of the specific components. The MOTOR POSITIONS AND ROTATION DIRECTIONS ARE CORRECT AND MATTER,
    /// because the flight physics applies thrust at those transforms. The fact that a Pixhawk is
    /// represented by a grey box does not.
    ///
    /// Every dimension marked [ESTIMATE] below is an engineering estimate, not a datasheet figure.
    /// </summary>
    public static class AirframeBuilder
    {
        private const string RootName = "ASTRA_UAV";
        private const string MaterialFolder = "Assets/ASTRA/Materials/Generated";

        // Layer conventions. Not created here - creating layers from script is unreliable across Unity
        // versions - but named so the setup document and the code agree.
        private const string GeneratedNotice =
            "Generated by AirframeBuilder. Regenerate rather than editing by hand: " +
            "hand edits are lost on the next rebuild.";

        [MenuItem("ASTRA/Build Airframe in Scene", false, 20)]
        public static void BuildMenu()
        {
            UavConfiguration config = FindConfiguration();
            if (config == null)
            {
                EditorUtility.DisplayDialog(
                    "ASTRA - no configuration found",
                    "No UavConfiguration asset exists in the project.\n\n" +
                    "Create one first:  Assets > Create > ASTRA > UAV Configuration\n\n" +
                    "The airframe geometry is derived from that asset, so the builder cannot run " +
                    "without it.",
                    "OK");
                return;
            }

            GameObject existing = GameObject.Find(RootName);
            if (existing != null)
            {
                bool replace = EditorUtility.DisplayDialog(
                    "ASTRA - airframe already in scene",
                    "An object named '" + RootName + "' already exists.\n\n" +
                    "Replacing it will destroy it and any manual changes made to it, including " +
                    "inspector references pointing at it from other objects.",
                    "Replace", "Cancel");
                if (!replace)
                {
                    return;
                }
                Undo.DestroyObjectImmediate(existing);
            }

            GameObject root = Build(config);

            Undo.RegisterCreatedObjectUndo(root, "Build ASTRA airframe");
            Selection.activeGameObject = root;
            EditorGUIUtility.PingObject(root);

            Debug.Log("[ASTRA] Airframe built. " + GeneratedNotice);
        }

        /// <summary>
        /// Constructs the airframe and returns its root.
        /// </summary>
        public static GameObject Build(UavConfiguration config)
        {
            // ---- Dimensions, all derived from the configuration ----
            float motorOffset = config.MotorAxisOffsetM;      // along each of X and Z
            float armLength = config.ArmLengthM;
            float propRadius = config.PropellerDiameterM * 0.5f;

            // [ESTIMATE] Frame plate: the Tarot 650 centre plate is roughly 220 mm across the carbon
            // top plate. Not measured.
            const float plateHalf = 0.110f;
            const float plateThickness = 0.006f;

            // [ESTIMATE] Arm tube: 16 mm carbon tube on the 650-class frames.
            const float armTubeDiameter = 0.016f;

            // [ESTIMATE] 5010-class outrunner: about 58 mm across the bell, 30 mm tall.
            const float motorDiameter = 0.058f;
            const float motorHeight = 0.030f;

            // ---- Materials ----
            Material carbonMat = GetOrCreateMaterial("ASTRA_Carbon", new Color(0.12f, 0.13f, 0.15f), 0.35f);
            Material aluminiumMat = GetOrCreateMaterial("ASTRA_Aluminium", new Color(0.52f, 0.54f, 0.57f), 0.25f);
            Material motorMat = GetOrCreateMaterial("ASTRA_Motor", new Color(0.24f, 0.26f, 0.30f), 0.30f);
            Material propMat = GetOrCreateMaterial("ASTRA_Propeller", new Color(0.08f, 0.08f, 0.09f), 0.55f);
            Material batteryMat = GetOrCreateMaterial("ASTRA_Battery", new Color(0.18f, 0.20f, 0.30f), 0.60f);
            Material pcbMat = GetOrCreateMaterial("ASTRA_PCB", new Color(0.05f, 0.24f, 0.14f), 0.55f);
            Material avionicsMat = GetOrCreateMaterial("ASTRA_Avionics", new Color(0.20f, 0.22f, 0.24f), 0.45f);
            Material sensorMat = GetOrCreateMaterial("ASTRA_Sensor", new Color(0.85f, 0.86f, 0.88f), 0.35f);
            Material futureMat = GetOrCreateMaterial("ASTRA_FutureHardware", new Color(0.35f, 0.45f, 0.60f), 0.40f);

            // ================================================================================
            // ROOT
            // ================================================================================
            GameObject root = new GameObject(RootName);
            root.transform.position = new Vector3(0f, 0.12f, 0f);

            // The primary collider. ONE simplified convex proxy rather than a collider on every part.
            //
            // Deliberate: a compound collider built from the propellers and the GPS mast would snag on
            // scenery and would make the aircraft's effective size depend on which cosmetic part
            // happened to stick out furthest. A single box sized to the propeller disc extents is a
            // predictable, slightly conservative footprint, which is what the avoidance margins are
            // computed against. It is an APPROXIMATION and is documented as one.
            BoxCollider hull = root.AddComponent<BoxCollider>();
            float hullHalfWidth = motorOffset + propRadius * 0.65f;
            hull.size = new Vector3(hullHalfWidth * 2f, 0.26f, hullHalfWidth * 2f);
            hull.center = new Vector3(0f, -0.03f, 0f);

            Rigidbody body = root.AddComponent<Rigidbody>();
            body.mass = config.MassKg;

            // ================================================================================
            // STRUCTURE
            // ================================================================================
            GameObject structureGroup = Group(root.transform, "Structure");

            GameObject plate = Primitive(PrimitiveType.Cube, structureGroup.transform, "Frame_CentrePlate",
                new Vector3(0f, 0f, 0f),
                new Vector3(plateHalf * 2f, plateThickness, plateHalf * 2f), carbonMat);
            Tag(plate, "Centre Frame Plate", "Tarot 650 Sport (assumed)", ComponentCategory.Structure,
                ImplementationStatus.Simulated, 180f, 0f,
                "Carbon fibre centre plate carrying the flight controller, power distribution and " +
                "companion computer. All four arms bolt to it, so every thrust and reaction load in " +
                "the airframe passes through this part.",
                "[UNVERIFIED] Frame identified as Tarot 650 Sport from the project brief. Plate " +
                "dimensions and mass are estimates; neither has been measured or taken from a " +
                "manufacturer drawing.");
            plate.GetComponent<UavComponent>().SetExplode(Vector3.zero, 0f);

            // ---- Arms ----
            // Built from the same offsets the motors use, so the arms cannot end up pointing somewhere
            // the motors are not.
            for (int i = 0; i < 4; i++)
            {
                Vector3 motorPos = MotorPosition(i, motorOffset);
                Vector3 direction = new Vector3(motorPos.x, 0f, motorPos.z).normalized;

                GameObject arm = Primitive(PrimitiveType.Cylinder, structureGroup.transform,
                    "Arm_" + (i + 1),
                    direction * (armLength * 0.5f),
                    new Vector3(armTubeDiameter, armLength * 0.5f, armTubeDiameter), carbonMat);

                // Unity's cylinder runs along its local Y with a height of 2 units, hence the 0.5
                // factor on the Y scale above and the rotation from up onto the arm direction here.
                arm.transform.localRotation = Quaternion.FromToRotation(Vector3.up, direction);

                Tag(arm, "Arm " + (i + 1), "16 mm carbon tube (assumed)", ComponentCategory.Structure,
                    ImplementationStatus.Simulated, 55f, 0f,
                    "Carbon fibre arm carrying motor " + (i + 1) + ". Transfers that rotor's thrust " +
                    "and reaction torque into the centre plate. Arm length sets the moment arm, and " +
                    "therefore how much roll and pitch authority a given thrust differential produces.",
                    "[ESTIMATE] Tube diameter and mass assumed. Arm length is derived from the " +
                    "configured " + config.WheelbaseM.ToString("F3") + " m wheelbase, which is " +
                    "itself unverified.");
                arm.GetComponent<UavComponent>().SetExplode(direction, 0.10f);
            }

            // ================================================================================
            // PROPULSION - the part that is functionally load-bearing
            // ================================================================================
            GameObject propulsionGroup = Group(root.transform, "Propulsion");
            MotorUnit[] motorUnits = new MotorUnit[4];

            for (int i = 0; i < 4; i++)
            {
                Vector3 motorPos = MotorPosition(i, motorOffset);
                Vector3 direction = new Vector3(motorPos.x, 0f, motorPos.z).normalized;

                // ---- Motor assembly root. THIS TRANSFORM IS PHYSICALLY SIGNIFICANT: ----
                // QuadcopterPhysics applies each rotor's thrust at this position, along this
                // transform's up axis. Moving it changes the aircraft's control authority. It is not
                // decoration.
                GameObject motorRoot = new GameObject(string.Format("Motor_{0}", i + 1));
                motorRoot.transform.SetParent(propulsionGroup.transform, false);
                motorRoot.transform.localPosition = motorPos + new Vector3(0f, plateThickness, 0f);

                GameObject motorBody = Primitive(PrimitiveType.Cylinder, motorRoot.transform,
                    "MotorBody",
                    new Vector3(0f, motorHeight * 0.5f, 0f),
                    new Vector3(motorDiameter, motorHeight * 0.5f, motorDiameter), motorMat);
                StripCollider(motorBody);

                // ---- Propeller ----
                GameObject propeller = new GameObject("Propeller");
                propeller.transform.SetParent(motorRoot.transform, false);
                propeller.transform.localPosition = new Vector3(0f, motorHeight + 0.008f, 0f);

                // Two blades. Built as one hub plus two blade boxes so the blades visibly sweep when
                // the hub spins, rather than a disc that looks stationary at every speed.
                GameObject hub = Primitive(PrimitiveType.Cylinder, propeller.transform, "Hub",
                    Vector3.zero, new Vector3(0.022f, 0.004f, 0.022f), propMat);
                StripCollider(hub);

                for (int blade = 0; blade < 2; blade++)
                {
                    GameObject bladeObj = Primitive(PrimitiveType.Cube, propeller.transform,
                        "Blade_" + (blade + 1),
                        new Vector3(propRadius * 0.5f * (blade == 0 ? 1f : -1f), 0f, 0f),
                        new Vector3(propRadius, 0.0035f, 0.026f), propMat);
                    StripCollider(bladeObj);

                    // A few degrees of pitch on the blade, so the propeller reads as a propeller
                    // rather than a flat paddle, and so the two blades are visibly handed.
                    // [COSMETIC] This angle is not the aerodynamic pitch and is not used by the
                    // thrust model, which takes pitch from the configuration.
                    float sign = blade == 0 ? 1f : -1f;
                    bladeObj.transform.localRotation = Quaternion.Euler(12f * sign, 0f, 0f);
                }

                // ---- Motion blur disc ----
                // Fades in at speed to stand in for a blade set moving far faster than the display can
                // resolve. Disabled at rest.
                GameObject blur = Primitive(PrimitiveType.Cylinder, propeller.transform, "BlurDisc",
                    Vector3.zero, new Vector3(propRadius * 2f, 0.0015f, propRadius * 2f), propMat);
                StripCollider(blur);
                blur.SetActive(false);

                // ---- The MotorUnit component ----
                MotorUnit unit = motorRoot.AddComponent<MotorUnit>();
                motorUnits[i] = unit;

                PropellerRotation spin = RotationForMotor(i);
                SerializedObject so = new SerializedObject(unit);
                so.FindProperty("motorIndex").intValue = i;
                so.FindProperty("rotation").enumValueIndex = (int)spin;
                so.FindProperty("propeller").objectReferenceValue = propeller.transform;
                so.FindProperty("blurDisc").objectReferenceValue = blur;
                so.ApplyModifiedPropertiesWithoutUndo();

                string spinName = spin == PropellerRotation.Clockwise
                    ? "clockwise" : "counter-clockwise";

                Tag(motorRoot, "Motor " + (i + 1) + " + Propeller",
                    "5010 360KV / 15x5.5 (assumed)", ComponentCategory.Propulsion,
                    ImplementationStatus.Simulated, 195f, 0f,
                    string.Format(
                        "Brushless outrunner and {0} propeller at the {1} position, rotating {2} " +
                        "viewed from above. Thrust is applied to the rigidbody at THIS transform, " +
                        "which is why roll and pitch emerge from thrust differentials rather than " +
                        "being commanded as torques. Its reaction torque about the yaw axis is what " +
                        "makes yaw control possible.",
                        (config.PropellerDiameterM / 0.0254f).ToString("F0") + " inch",
                        PositionName(i), spinName),
                    "[UNVERIFIED - FLIGHT SAFETY RELEVANT] Motor and propeller identified from the " +
                    "project brief, not from a datasheet. The maximum thrust figure in " +
                    "UavConfiguration is the single most important unverified number in the whole " +
                    "model: every performance claim depends on it. It must be replaced with a " +
                    "manufacturer thrust table or a measured static thrust test before any figure " +
                    "from this simulation is quoted as a specification.");
                motorRoot.GetComponent<UavComponent>().SetExplode(direction + Vector3.up * 0.4f, 0.16f);

                // ---- ESC, mounted on the arm inboard of the motor ----
                GameObject esc = Primitive(PrimitiveType.Cube, propulsionGroup.transform,
                    "ESC_" + (i + 1),
                    direction * (armLength * 0.55f) + new Vector3(0f, plateThickness + 0.008f, 0f),
                    new Vector3(0.024f, 0.010f, 0.052f), pcbMat);
                esc.transform.localRotation = Quaternion.FromToRotation(Vector3.forward, direction);
                Tag(esc, "ESC " + (i + 1), "40 A BLHeli-class (assumed)", ComponentCategory.Propulsion,
                    ImplementationStatus.Simulated, 28f, 0f,
                    "Electronic speed controller for motor " + (i + 1) + ". Converts the flight " +
                    "controller's throttle signal into three-phase drive. In this simulation the " +
                    "ESC is modelled only as the first-order lag between a commanded and an actual " +
                    "rotor speed, which is the behaviour that affects flight.",
                    "[UNVERIFIED - FLIGHT SAFETY RELEVANT] The brief specifies 40 A ESCs but does " +
                    "not state their voltage rating. A 6S pack is 25.2 V fully charged, and many 40 A " +
                    "ESCs are rated only to 4S. Confirm the ESCs are rated for 6S before connecting " +
                    "the pack. See Docs/10-UAV-Hardware-Layout.md.");
                esc.GetComponent<UavComponent>().SetExplode(direction, 0.12f);
            }

            // ================================================================================
            // POWER
            // ================================================================================
            GameObject powerGroup = Group(root.transform, "Power");

            GameObject battery = Primitive(PrimitiveType.Cube, powerGroup.transform, "Battery_6S",
                new Vector3(0f, -0.038f, 0f),
                new Vector3(0.046f, 0.050f, 0.150f), batteryMat);
            Tag(battery, "Battery - 6S 6200 mAh LiPo", "6S1P 22.2 V (assumed)",
                ComponentCategory.Power, ImplementationStatus.Simulated, 900f, 0f,
                string.Format(
                    "Six-cell lithium polymer pack, {0} mAh nominal, {1:F1} V nominal, about " +
                    "{2:F0} Wh. Mounted below the centre plate and on the centre line so the centre " +
                    "of mass stays under the rotor plane. Modelled with a realistic discharge curve " +
                    "and internal resistance, so voltage sags under load and the sag reduces " +
                    "available thrust.",
                    config.BatteryCapacityMah, config.NominalVoltage, config.BatteryEnergyWh),
                string.Format(
                    "[ESTIMATE] Mass and physical dimensions are estimates. The pack's C rating is " +
                    "not stated in the brief; the modelled full-throttle draw implies a minimum of " +
                    "about {0:F0}C, so a pack below that rating would sag badly and could be damaged. " +
                    "Verify the C rating on the pack label.",
                    config.MinimumBatteryCRating));
            battery.GetComponent<UavComponent>().SetExplode(Vector3.down, 0.18f);

            GameObject pdb = Primitive(PrimitiveType.Cube, powerGroup.transform, "PowerDistributionBoard",
                new Vector3(0f, -0.008f, 0f), new Vector3(0.070f, 0.004f, 0.070f), pcbMat);
            Tag(pdb, "Power Distribution Board", "", ComponentCategory.Power,
                ImplementationStatus.Simulated, 25f, 0f,
                "Splits the pack's output to the four ESCs. Carries the full propulsion current, so " +
                "its trace width and connector rating set a hard ceiling on the aircraft's power.",
                string.Format(
                    "[UNVERIFIED] No PDB part is named in the brief. Modelled current at full " +
                    "throttle is about {0:F0} A total, so the board and every connector in the " +
                    "propulsion path must be rated above that with margin.",
                    config.FullThrottleCurrentA));

            GameObject powerModule = Primitive(PrimitiveType.Cube, powerGroup.transform, "PowerModule",
                new Vector3(0.055f, -0.008f, -0.040f), new Vector3(0.030f, 0.012f, 0.040f), pcbMat);
            Tag(powerModule, "Power Module / Current Sensor", "", ComponentCategory.Power,
                ImplementationStatus.Simulated, 30f, 0f,
                "Measures pack voltage and current for the flight controller and supplies regulated " +
                "5 V to it. This is the sensor the battery telemetry and the low-voltage failsafe " +
                "depend on, so its accuracy determines whether the failsafe fires at the right time.",
                "[UNVERIFIED - FLIGHT SAFETY RELEVANT] This is the most likely incompatibility in " +
                "the whole build. The power module bundled with a Pixhawk 2.4.8 is commonly rated to " +
                "4S / roughly 18 V, while a 6S pack reaches 25.2 V fully charged. Connecting a 4S " +
                "module to a 6S pack can destroy it and take the flight controller with it. Confirm " +
                "the module's voltage rating BEFORE first power-up, or fit a 6S-rated module or a " +
                "separate BEC. See Docs/10-UAV-Hardware-Layout.md.");

            GameObject ubec = Primitive(PrimitiveType.Cube, powerGroup.transform, "UBEC_5V",
                new Vector3(-0.055f, -0.008f, -0.040f), new Vector3(0.028f, 0.010f, 0.036f), pcbMat);
            Tag(ubec, "5 V / 5 A UBEC", "", ComponentCategory.Power,
                ImplementationStatus.Simulated, 20f, 0f,
                "Steps the pack voltage down to 5 V for the companion computer, which needs more " +
                "current than the flight controller's own regulator can supply.",
                "[UNVERIFIED] A Raspberry Pi 5 can demand around 5 A at 5 V under load, so a " +
                "marginal BEC will brown it out mid-flight - which would look exactly like a " +
                "software crash and would be diagnosed as one. Verify the BEC's continuous rating, " +
                "not its peak.");

            BatterySystem batterySystem = root.AddComponent<BatterySystem>();
            SerializedObject batterySo = new SerializedObject(batterySystem);
            batterySo.FindProperty("config").objectReferenceValue = config;
            batterySo.ApplyModifiedPropertiesWithoutUndo();

            // ================================================================================
            // AVIONICS
            // ================================================================================
            GameObject avionicsGroup = Group(root.transform, "Avionics");

            GameObject pixhawk = Primitive(PrimitiveType.Cube, avionicsGroup.transform, "FlightController",
                new Vector3(0f, plateThickness + 0.010f, 0.010f),
                new Vector3(0.050f, 0.016f, 0.081f), avionicsMat);
            Tag(pixhawk, "Flight Controller", "Pixhawk 2.4.8 (assumed)",
                ComponentCategory.FlightControl, ImplementationStatus.Simulated, 38f, 0.25f,
                "Runs the attitude and position control loops and the flight state machine, and " +
                "houses the IMU, barometer and internal compass. In ASTRA its role is played by " +
                "FlightControlSystem, which reproduces the same cascaded control architecture and " +
                "the same arming and failsafe logic.",
                "[SIMULATED] The control loops in this project are a faithful reproduction of the " +
                "ARCHITECTURE a Pixhawk running ArduPilot uses, and the gains are expressed in the " +
                "same units so they transfer. They are NOT flight-certified firmware: there is no " +
                "sensor redundancy, no EKF with innovation gating, no watchdog and none of the field " +
                "history that real autopilot software carries.");
            pixhawk.GetComponent<UavComponent>().SetExplode(Vector3.up, 0.14f);

            GameObject pi = Primitive(PrimitiveType.Cube, avionicsGroup.transform, "CompanionComputer",
                new Vector3(0f, plateThickness + 0.032f, -0.012f),
                new Vector3(0.056f, 0.014f, 0.085f), pcbMat);
            Tag(pi, "Companion Computer", "Raspberry Pi 5 (assumed)", ComponentCategory.Compute,
                ImplementationStatus.Simulated, 65f, 3.0f,
                "Carries the perception and route planning that is too heavy for the flight " +
                "controller: obstacle detection, the planner, and the visual navigation used when " +
                "GPS is unavailable. Talks to the flight controller over serial, as MAVLink.",
                "[ESTIMATE] Current draw is an estimate and depends heavily on load; a Pi 5 running " +
                "vision continuously draws considerably more than one sitting idle. Thermal " +
                "behaviour inside an airframe is not modelled at all, and a Pi 5 under sustained " +
                "vision load will throttle without active cooling - which would show up in flight " +
                "as the perception rate quietly dropping.");
            pi.GetComponent<UavComponent>().SetExplode(Vector3.up, 0.20f);

            // ================================================================================
            // NAVIGATION SENSORS
            // ================================================================================
            GameObject navGroup = Group(root.transform, "Navigation");

            GameObject gpsMast = Primitive(PrimitiveType.Cylinder, navGroup.transform, "GPS_Mast",
                new Vector3(0f, plateThickness + 0.045f, -0.070f),
                new Vector3(0.008f, 0.045f, 0.008f), aluminiumMat);
            StripCollider(gpsMast);

            GameObject gps = Primitive(PrimitiveType.Cylinder, navGroup.transform, "GPS_Compass",
                new Vector3(0f, plateThickness + 0.094f, -0.070f),
                new Vector3(0.052f, 0.005f, 0.052f), sensorMat);
            Tag(gps, "GNSS Receiver + Compass", "", ComponentCategory.Navigation,
                ImplementationStatus.Simulated, 32f, 0.10f,
                "Provides absolute position and heading. Raised on a mast and set back from the " +
                "power wiring because the magnetometer inside it is easily corrupted by the magnetic " +
                "field of the propulsion currents - which is a real and frequently underestimated " +
                "source of heading error on multirotors.",
                "[SIMULATED] Simulated with representative noise, dilution of precision and " +
                "satellite count. The GPS-denied demonstration works by disabling this provider, " +
                "which is an honest way to show the consequence but is not the same as a real " +
                "jamming or multipath environment, where degradation is gradual and the receiver " +
                "reports a fix it should not be trusted with.");
            gps.GetComponent<UavComponent>().SetExplode(Vector3.up, 0.16f);

            GameObject camera = Primitive(PrimitiveType.Cube, navGroup.transform, "Camera",
                new Vector3(0f, -0.030f, 0.090f), new Vector3(0.034f, 0.026f, 0.030f), avionicsMat);
            Tag(camera, "Forward Camera", "", ComponentCategory.Payload,
                ImplementationStatus.Demonstration, 45f, 0.35f,
                "Forward-looking camera. Feeds the visual navigation used when GPS is unavailable, " +
                "and provides the operator's first-person view.",
                "[DEMONSTRATION] The visual odometry driven by this camera is a SIMPLIFIED STAND-IN, " +
                "not an implementation of visual SLAM. It does not extract features, does not match " +
                "them between frames, does not perform bundle adjustment and does not close loops. " +
                "It reproduces the OBSERVABLE BEHAVIOUR of a VIO system - a drifting position " +
                "estimate whose uncertainty grows without absolute reference - so that the " +
                "consequence of losing GPS can be shown honestly. It must not be described as SLAM.");
            camera.GetComponent<UavComponent>().SetExplode(Vector3.forward, 0.14f);

            GameObject lidar = Primitive(PrimitiveType.Cylinder, navGroup.transform, "LiDAR_Future",
                new Vector3(0f, plateThickness + 0.055f, 0.050f),
                new Vector3(0.060f, 0.020f, 0.060f), futureMat);
            Tag(lidar, "LiDAR", "", ComponentCategory.Navigation,
                ImplementationStatus.FutureHardware, 0f, 0f,
                "Mounting provision and software interface for a scanning LiDAR, for obstacle " +
                "detection independent of lighting. The IObstacleDetector interface it would " +
                "implement already exists, so adding the sensor would not require changes to the " +
                "planner.",
                "[FUTURE HARDWARE] NOT PRESENT ON THE AIRCRAFT. Not purchased, not mounted, not " +
                "integrated. Its mass is entered as zero deliberately, so the mass budget reflects " +
                "the aircraft that exists. Shown in a distinct colour so it cannot be mistaken for " +
                "fitted equipment.");
            lidar.GetComponent<UavComponent>().SetExplode(Vector3.up, 0.22f);

            // ================================================================================
            // COMMUNICATION
            // ================================================================================
            GameObject commsGroup = Group(root.transform, "Communication");

            GameObject receiver = Primitive(PrimitiveType.Cube, commsGroup.transform, "RC_Receiver",
                new Vector3(0.048f, plateThickness + 0.010f, -0.048f),
                new Vector3(0.020f, 0.010f, 0.042f), avionicsMat);
            Tag(receiver, "RC Receiver", "FlySky iA6B (assumed)", ComponentCategory.Communication,
                ImplementationStatus.Simulated, 15f, 0.05f,
                "Receives the operator's manual control link. Loss of this link is what triggers the " +
                "return-to-launch failsafe, which is one of the scenarios the simulator demonstrates.",
                "[UNVERIFIED] Receiver identified from the brief. Its actual channel count and " +
                "protocol have not been confirmed against a datasheet.");

            GameObject telemetry = Primitive(PrimitiveType.Cube, commsGroup.transform, "TelemetryRadio",
                new Vector3(-0.048f, plateThickness + 0.010f, -0.048f),
                new Vector3(0.022f, 0.010f, 0.042f), avionicsMat);
            Tag(telemetry, "Telemetry Radio", "", ComponentCategory.Communication,
                ImplementationStatus.Simulated, 20f, 0.20f,
                "Carries the MAVLink telemetry stream to the ground station. This is the link the " +
                "ground control interface reads, and its latency and packet loss are what make a " +
                "remote operator's view of the aircraft lag behind reality.",
                "[UNVERIFIED] No specific radio is named in the brief. Range and link budget are " +
                "not modelled; link quality in the simulation is a representative figure, not a " +
                "propagation calculation.");

            // ================================================================================
            // LANDING GEAR
            // ================================================================================
            GameObject gearGroup = Group(root.transform, "LandingGear");

            for (int i = 0; i < 4; i++)
            {
                Vector3 motorPos = MotorPosition(i, motorOffset);
                Vector3 direction = new Vector3(motorPos.x, 0f, motorPos.z).normalized;
                Vector3 footBase = direction * (armLength * 0.42f);

                GameObject leg = Primitive(PrimitiveType.Cylinder, gearGroup.transform,
                    "Leg_" + (i + 1),
                    footBase + new Vector3(0f, -0.055f, 0f),
                    new Vector3(0.012f, 0.055f, 0.012f), aluminiumMat);

                // Splay the legs outward so the footprint is wider than the mounting points, which is
                // what stops a multirotor tipping on touchdown.
                leg.transform.localRotation = Quaternion.FromToRotation(
                    Vector3.up, (Vector3.up * 3f + direction).normalized);

                Tag(leg, "Landing Leg " + (i + 1), "", ComponentCategory.LandingGear,
                    ImplementationStatus.Simulated, 45f, 0f,
                    "Supports the aircraft on the ground and holds the battery and camera clear of " +
                    "the surface. The footprint width is what determines how much slope the aircraft " +
                    "can be armed on without tipping onto its propellers.",
                    "[ESTIMATE] Geometry and mass are estimates. Gear compliance and touchdown " +
                    "energy absorption are not modelled: contact is handled by the single hull " +
                    "collider, so a hard landing does not deform anything.");
                leg.GetComponent<UavComponent>().SetExplode(direction + Vector3.down * 2f, 0.12f);
            }

            // ================================================================================
            // BEHAVIOUR COMPONENTS AND WIRING
            // ================================================================================
            QuadcopterPhysics physics = root.AddComponent<QuadcopterPhysics>();
            SerializedObject physicsSo = new SerializedObject(physics);
            physicsSo.FindProperty("config").objectReferenceValue = config;
            physicsSo.FindProperty("battery").objectReferenceValue = batterySystem;

            SerializedProperty motorsProp = physicsSo.FindProperty("motors");
            motorsProp.arraySize = 4;
            for (int i = 0; i < 4; i++)
            {
                motorsProp.GetArrayElementAtIndex(i).objectReferenceValue = motorUnits[i];
            }
            physicsSo.ApplyModifiedPropertiesWithoutUndo();

            FlightControlSystem controller = root.AddComponent<FlightControlSystem>();
            SerializedObject controllerSo = new SerializedObject(controller);
            controllerSo.FindProperty("config").objectReferenceValue = config;
            controllerSo.FindProperty("physics").objectReferenceValue = physics;
            controllerSo.ApplyModifiedPropertiesWithoutUndo();

            ManualFlightInput input = root.AddComponent<ManualFlightInput>();
            SerializedObject inputSo = new SerializedObject(input);
            inputSo.FindProperty("flightController").objectReferenceValue = controller;
            inputSo.ApplyModifiedPropertiesWithoutUndo();

            // Report the mass budget against the configured mass. A discrepancy here is worth seeing:
            // it means the component estimates and the mass used by the physics disagree, and one of
            // them is wrong.
            ReportMassBudget(root, config);

            return root;
        }

        // ====================================================================================
        // GEOMETRY
        // ====================================================================================

        /// <summary>
        /// Motor position for the given index, matching MotorMixer's QuadX ordering exactly.
        ///
        /// This must agree with MotorMixer and with MotorUnit's rotation assignment, or the aircraft
        /// will be uncontrollable in a way that is very hard to diagnose - it would roll when told to
        /// pitch, or yaw the wrong way. The single source of truth is the mixer's documented layout:
        ///
        ///   0 = front-right, 1 = rear-left, 2 = front-left, 3 = rear-right
        ///
        /// with +Z forward and +X right.
        /// </summary>
        private static Vector3 MotorPosition(int index, float offset)
        {
            switch (index)
            {
                case 0: return new Vector3(offset, 0f, offset);     // front-right
                case 1: return new Vector3(-offset, 0f, -offset);   // rear-left
                case 2: return new Vector3(-offset, 0f, offset);    // front-left
                case 3: return new Vector3(offset, 0f, -offset);    // rear-right
                default: return Vector3.zero;
            }
        }

        /// <summary>
        /// Rotation direction per motor. Diagonal pairs share a direction so their reaction torques
        /// cancel in hover; the difference between the pairs is what produces yaw.
        /// Motors 0 and 1 are counter-clockwise, 2 and 3 clockwise, matching MotorMixer.
        /// </summary>
        private static PropellerRotation RotationForMotor(int index)
        {
            return (index == 0 || index == 1)
                ? PropellerRotation.CounterClockwise
                : PropellerRotation.Clockwise;
        }

        private static string PositionName(int index)
        {
            switch (index)
            {
                case 0: return "front-right";
                case 1: return "rear-left";
                case 2: return "front-left";
                case 3: return "rear-right";
                default: return "unknown";
            }
        }

        // ====================================================================================
        // BUILD HELPERS
        // ====================================================================================

        private enum PrimitiveType { Cube, Cylinder }

        private static GameObject Group(Transform parent, string name)
        {
            GameObject group = new GameObject(name);
            group.transform.SetParent(parent, false);
            return group;
        }

        private static GameObject Primitive(PrimitiveType type, Transform parent, string name,
                                            Vector3 localPosition, Vector3 scale, Material material)
        {
            GameObject go = GameObject.CreatePrimitive(
                type == PrimitiveType.Cube
                    ? UnityEngine.PrimitiveType.Cube
                    : UnityEngine.PrimitiveType.Cylinder);

            go.name = name;
            go.transform.SetParent(parent, false);
            go.transform.localPosition = localPosition;
            go.transform.localScale = scale;

            Renderer renderer = go.GetComponent<Renderer>();
            if (renderer != null && material != null)
            {
                renderer.sharedMaterial = material;
            }

            // Every cosmetic part loses its collider. The airframe has ONE collider, on the root.
            StripCollider(go);

            return go;
        }

        /// <summary>
        /// Removes the collider a Unity primitive comes with.
        ///
        /// Necessary rather than tidy. Child colliders on a rigidbody form a compound collider, so
        /// leaving them would mean the propeller blades and the GPS mast were part of the aircraft's
        /// collision shape. The blades sweep a 380 mm disc, so the aircraft's effective size would
        /// change with rotor angle, and obstacle clearances would become unrepeatable.
        /// </summary>
        private static void StripCollider(GameObject go)
        {
            Collider collider = go.GetComponent<Collider>();
            if (collider != null)
            {
                Object.DestroyImmediate(collider);
            }
        }

        private static void Tag(GameObject go, string name, string designation,
                                ComponentCategory category, ImplementationStatus status,
                                float massGrams, float currentA, string description, string notes)
        {
            UavComponent component = go.GetComponent<UavComponent>();
            if (component == null)
            {
                component = go.AddComponent<UavComponent>();
            }
            component.Configure(name, designation, category, status, massGrams, currentA,
                                description, notes);
        }

        // ====================================================================================
        // MATERIALS
        // ====================================================================================

        /// <summary>
        /// Fetches or creates a URP material asset.
        ///
        /// Saved as an asset rather than created in memory so that the airframe survives a scene
        /// reload: a runtime-created material is not serialised, and the airframe would come back with
        /// pink magenta placeholders after a restart.
        /// </summary>
        private static Material GetOrCreateMaterial(string name, Color colour, float smoothness)
        {
            string path = MaterialFolder + "/" + name + ".mat";

            Material existing = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (existing != null)
            {
                return existing;
            }

            EnsureFolder(MaterialFolder);

            // URP's Lit shader. Falling back rather than failing, because a project that has not
            // finished importing URP yet should still produce a visible airframe rather than an error.
            Shader shader = Shader.Find("Universal Render Pipeline/Lit");
            if (shader == null)
            {
                shader = Shader.Find("Standard");
                Debug.LogWarning(
                    "[ASTRA] URP Lit shader not found, falling back to Standard. If the project is " +
                    "meant to be on URP, check that the render pipeline asset is assigned in " +
                    "Project Settings > Graphics.");
            }
            if (shader == null)
            {
                Debug.LogError("[ASTRA] No usable shader found. Airframe materials will be missing.");
                return null;
            }

            Material material = new Material(shader);
            material.name = name;

            // URP and the built-in Standard shader use different property names for the same thing.
            if (material.HasProperty("_BaseColor"))
            {
                material.SetColor("_BaseColor", colour);
            }
            if (material.HasProperty("_Color"))
            {
                material.SetColor("_Color", colour);
            }
            if (material.HasProperty("_Smoothness"))
            {
                material.SetFloat("_Smoothness", smoothness);
            }
            if (material.HasProperty("_Glossiness"))
            {
                material.SetFloat("_Glossiness", smoothness);
            }
            if (material.HasProperty("_Metallic"))
            {
                material.SetFloat("_Metallic", 0.15f);
            }

            AssetDatabase.CreateAsset(material, path);
            return material;
        }

        private static void EnsureFolder(string folder)
        {
            if (AssetDatabase.IsValidFolder(folder))
            {
                return;
            }

            string[] parts = folder.Split('/');
            string running = parts[0];   // "Assets"
            for (int i = 1; i < parts.Length; i++)
            {
                string next = running + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                {
                    AssetDatabase.CreateFolder(running, parts[i]);
                }
                running = next;
            }
        }

        // ====================================================================================
        // CONFIGURATION LOOKUP
        // ====================================================================================

        private static UavConfiguration FindConfiguration()
        {
            string[] guids = AssetDatabase.FindAssets("t:" + typeof(UavConfiguration).FullName);
            if (guids == null || guids.Length == 0)
            {
                // FindAssets with a fully-qualified type name can miss depending on how the type is
                // resolved, so retry with the short name before giving up.
                guids = AssetDatabase.FindAssets("t:UavConfiguration");
            }
            if (guids == null || guids.Length == 0)
            {
                return null;
            }

            string path = AssetDatabase.GUIDToAssetPath(guids[0]);
            if (guids.Length > 1)
            {
                Debug.LogWarning(string.Format(
                    "[ASTRA] {0} UavConfiguration assets found. Using '{1}'. Having more than one " +
                    "invites the airframe and the physics to be configured from different assets.",
                    guids.Length, path));
            }
            return AssetDatabase.LoadAssetAtPath<UavConfiguration>(path);
        }

        // ====================================================================================
        // MASS BUDGET
        // ====================================================================================

        /// <summary>
        /// Sums the per-component mass estimates and compares them with the configured total.
        ///
        /// Worth doing automatically. The configured mass drives the physics and the component masses
        /// drive the mass budget shown to an examiner, and if the two disagree then one of the numbers
        /// being presented is wrong. Reporting the difference means the discrepancy gets noticed
        /// during development rather than during a question from the floor.
        /// </summary>
        private static void ReportMassBudget(GameObject root, UavConfiguration config)
        {
            UavComponent[] components = root.GetComponentsInChildren<UavComponent>(true);
            float totalGrams = 0f;
            int futureCount = 0;

            for (int i = 0; i < components.Length; i++)
            {
                if (components[i].Status == ImplementationStatus.FutureHardware)
                {
                    futureCount++;
                    continue;
                }
                totalGrams += components[i].MassGrams;
            }

            float configuredGrams = config.MassKg * 1000f;
            float differenceGrams = configuredGrams - totalGrams;
            float percent = configuredGrams > 1f ? (differenceGrams / configuredGrams * 100f) : 0f;

            string summary = string.Format(
                "[ASTRA] Airframe built: {0} tagged components ({1} marked FUTURE HARDWARE and " +
                "excluded from the mass budget).\n" +
                "Mass budget from component estimates: {2:F0} g\n" +
                "Mass used by the physics (UavConfiguration): {3:F0} g\n" +
                "Unaccounted: {4:F0} g ({5:F0}% of total) - wiring, fasteners, connectors, " +
                "heat-shrink and estimation error.\n" +
                "ALL component masses are ESTIMATES. None has been weighed.",
                components.Length, futureCount, totalGrams, configuredGrams,
                differenceGrams, percent);

            if (differenceGrams < 0f)
            {
                Debug.LogWarning(summary + "\nThe component estimates now EXCEED the configured " +
                    "mass, which means the configured mass is too low or an estimate is too high. " +
                    "One of the two numbers being presented is wrong.");
            }
            else
            {
                Debug.Log(summary);
            }
        }
    }
}
