using System;
using UnityEngine;

namespace Astra.Contracts
{
    /// <summary>
    /// Health of a subsystem, as reported to the diagnostics panel.
    /// </summary>
    public enum SubsystemStatus
    {
        /// <summary>Not present or not powered.</summary>
        Offline = 0,

        /// <summary>Present, initialising, not yet usable.</summary>
        Initialising = 1,

        /// <summary>Nominal.</summary>
        Ok = 2,

        /// <summary>Functioning but degraded. Mission may continue with reduced confidence.</summary>
        Warning = 3,

        /// <summary>Failed. Any consumer must treat its output as invalid.</summary>
        Error = 4
    }

    /// <summary>
    /// Where a provider's data actually comes from.
    ///
    /// This exists to satisfy a hard project requirement: nothing in ASTRA may present simulated
    /// output as though it were real. Every provider declares its own provenance, the UI reads
    /// this enum, and the corresponding badge is rendered next to the readout. That makes it
    /// structurally difficult to overstate the system's maturity, rather than relying on whoever
    /// writes the UI label to remember.
    /// </summary>
    public enum DataProvenance
    {
        /// <summary>Generated by the simulator. Must be labelled SIMULATED in the UI.</summary>
        Simulated = 0,

        /// <summary>A deliberately simplified stand-in for a real algorithm, for demonstration
        /// purposes. Must be labelled DEMONSTRATION in the UI. Used by the visual-odometry and
        /// SLAM stand-ins, which are NOT real implementations of those algorithms.</summary>
        Demonstration = 1,

        /// <summary>Live data from physical hardware.</summary>
        Hardware = 2,

        /// <summary>Mixed simulated and hardware sources.</summary>
        Hybrid = 3,

        /// <summary>Nothing is implemented yet; this is a placeholder for future hardware.</summary>
        FutureHardware = 4
    }

    /// <summary>Human-readable badges for DataProvenance, used directly by UI code.</summary>
    public static class DataProvenanceLabels
    {
        public static string ToBadge(DataProvenance provenance)
        {
            switch (provenance)
            {
                case DataProvenance.Simulated: return "SIMULATED";
                case DataProvenance.Demonstration: return "DEMONSTRATION";
                case DataProvenance.Hardware: return "HARDWARE";
                case DataProvenance.Hybrid: return "HYBRID";
                case DataProvenance.FutureHardware: return "FUTURE HARDWARE";
                default: return "UNKNOWN";
            }
        }

        /// <summary>
        /// Colour for the badge. Simulated and demonstration deliberately get an attention-drawing
        /// amber rather than a comfortable grey, so a viewer cannot overlook them.
        /// </summary>
        public static Color ToColour(DataProvenance provenance)
        {
            switch (provenance)
            {
                case DataProvenance.Simulated: return new Color(0.98f, 0.71f, 0.20f);
                case DataProvenance.Demonstration: return new Color(0.98f, 0.55f, 0.20f);
                case DataProvenance.Hardware: return new Color(0.30f, 0.85f, 0.45f);
                case DataProvenance.Hybrid: return new Color(0.40f, 0.70f, 0.95f);
                case DataProvenance.FutureHardware: return new Color(0.55f, 0.55f, 0.60f);
                default: return Color.grey;
            }
        }
    }

    /// <summary>
    /// A single inertial measurement sample, in the body frame.
    ///
    /// UNITS follow the convention of real IMU drivers so a hardware adapter needs no rescaling:
    /// acceleration in m/s^2, angular rate in rad/s. Note that a real accelerometer measures
    /// SPECIFIC FORCE, meaning it reads ~9.81 m/s^2 upward while sitting still on a bench, and
    /// reads ~0 in free fall. Our simulated IMU reproduces that, because code which assumes
    /// otherwise breaks the moment it meets a real sensor.
    /// </summary>
    public struct ImuSample
    {
        /// <summary>Specific force in the body frame, m/s^2, gravity included.</summary>
        public Vector3 Acceleration;

        /// <summary>Angular rate in the body frame, rad/s.</summary>
        public Vector3 AngularVelocity;

        /// <summary>Sensor temperature in degrees Celsius. Real IMUs drift with temperature.</summary>
        public float TemperatureC;

        /// <summary>Seconds since simulation start at which this sample was taken.</summary>
        public double Timestamp;

        public bool IsValid;
    }

    /// <summary>
    /// A GNSS fix.
    ///
    /// Field names mirror MAVLink's GPS_RAW_INT so the mapping to a real Pixhawk stream is
    /// obvious. HDOP/VDOP are dimensionless dilution-of-precision figures where lower is better;
    /// below 1.0 is excellent, above 5.0 is poor.
    /// </summary>
    public struct GpsFix
    {
        public double Latitude;
        public double Longitude;

        /// <summary>Altitude in metres. See GeoCoordinate for the datum caveat.</summary>
        public double Altitude;

        /// <summary>Number of satellites used in the solution.</summary>
        public int SatelliteCount;

        /// <summary>Horizontal dilution of precision, dimensionless.</summary>
        public float Hdop;

        /// <summary>Vertical dilution of precision, dimensionless.</summary>
        public float Vdop;

        /// <summary>Ground velocity in the ENU frame, m/s.</summary>
        public Vector3 VelocityEnu;

        /// <summary>0 = no fix, 1 = dead reckoning, 2 = 2D, 3 = 3D, 4 = DGPS, 5 = RTK float, 6 = RTK fixed.</summary>
        public int FixType;

        public double Timestamp;

        /// <summary>True only when the fix is usable for navigation, i.e. FixType >= 3.</summary>
        public bool HasFix
        {
            get { return FixType >= 3; }
        }

        /// <summary>
        /// Estimated horizontal position error in metres, derived from HDOP.
        /// Uses the standard rule of thumb: error ~= HDOP * UERE, with UERE taken as 3 m for a
        /// consumer receiver. [APPROXIMATE - engineering estimate, not a measured figure.]
        /// </summary>
        public float EstimatedHorizontalErrorM
        {
            get { return Hdop * 3.0f; }
        }
    }

    /// <summary>Barometric pressure sample. Real barometers are the primary altitude source on
    /// most multirotors because GNSS vertical accuracy is poor.</summary>
    public struct BarometerSample
    {
        /// <summary>Absolute pressure in pascals.</summary>
        public float PressurePa;

        /// <summary>Pressure altitude in metres, derived from the barometric formula.</summary>
        public float AltitudeM;

        public float TemperatureC;
        public double Timestamp;
        public bool IsValid;
    }

    /// <summary>Magnetometer sample in the body frame, in microtesla.</summary>
    public struct MagnetometerSample
    {
        public Vector3 FieldUt;

        /// <summary>Heading derived from the field vector, degrees clockwise from true north.</summary>
        public float HeadingDegrees;

        public double Timestamp;
        public bool IsValid;
    }

    /// <summary>
    /// A fused estimate of the vehicle's state, and the honest uncertainty attached to it.
    ///
    /// The Confidence field is the reason this type exists in this shape. A navigation stack that
    /// returns only a position invites downstream code to trust it absolutely. Carrying the
    /// covariance and a scalar confidence alongside forces consumers to acknowledge that this is
    /// an ESTIMATE, which is the whole point of the GPS-denied demonstration.
    /// </summary>
    public struct PoseEstimate
    {
        /// <summary>Estimated position in Unity world space (x=East, y=Up, z=North), metres.</summary>
        public Vector3 Position;

        /// <summary>Estimated orientation.</summary>
        public Quaternion Orientation;

        /// <summary>Estimated velocity in world space, m/s.</summary>
        public Vector3 Velocity;

        /// <summary>
        /// Standard deviation of the position estimate along each world axis, metres.
        /// Rendered as the uncertainty ellipsoid in the perception view.
        /// </summary>
        public Vector3 PositionStdDev;

        /// <summary>Standard deviation of the heading estimate, degrees.</summary>
        public float HeadingStdDevDeg;

        /// <summary>
        /// Overall confidence in [0,1]. 1 means the estimator considers itself well constrained.
        /// This is a heuristic summary for the operator, not a rigorous probability.
        /// </summary>
        public float Confidence;

        /// <summary>Which estimator produced this, for display: "GNSS+BARO", "VIO", "DEAD RECKONING".</summary>
        public string SourceName;

        public DataProvenance Provenance;
        public double Timestamp;
        public bool IsValid;

        public static PoseEstimate Invalid
        {
            get
            {
                PoseEstimate p = new PoseEstimate();
                p.IsValid = false;
                p.Confidence = 0f;
                p.SourceName = "NONE";
                p.Orientation = Quaternion.identity;
                return p;
            }
        }
    }

    /// <summary>
    /// One detected obstacle, as the perception layer reports it.
    ///
    /// Deliberately expressed in terms a real detector could actually supply. A stereo camera or
    /// LiDAR gives you a bearing, a range and an extent; it does not give you the obstacle's
    /// identity, mass or intent. Keeping this struct to observable quantities stops the planner
    /// from quietly depending on omniscient information that no real sensor would provide.
    /// </summary>
    public struct ObstacleReading
    {
        /// <summary>Stable identifier across frames, assigned by the tracker.</summary>
        public int TrackId;

        /// <summary>Closest observed point on the obstacle, in world space.</summary>
        public Vector3 ClosestPoint;

        /// <summary>Centre of the observed extent, world space.</summary>
        public Vector3 Centre;

        /// <summary>Half-extents of an axis-aligned box bounding the observation, metres.</summary>
        public Vector3 HalfExtents;

        /// <summary>Range from the sensor to ClosestPoint, metres.</summary>
        public float DistanceM;

        /// <summary>Bearing to the obstacle relative to the vehicle nose, degrees, positive right.</summary>
        public float RelativeBearingDeg;

        /// <summary>
        /// Estimated velocity of the obstacle in world space, m/s. Zero for anything the tracker
        /// considers static. Estimated by finite difference across frames, so it is noisy for
        /// small or briefly-seen objects.
        /// </summary>
        public Vector3 Velocity;

        /// <summary>True once the tracker has seen it long enough to trust the velocity estimate.</summary>
        public bool VelocityIsReliable;

        /// <summary>How many consecutive frames this track has been observed.</summary>
        public int ObservationCount;

        /// <summary>Simulation time of the most recent observation.</summary>
        public double LastSeen;

        /// <summary>Which sensor produced it, for the perception overlay.</summary>
        public string SensorName;

        /// <summary>Coarse classification. Honest about being coarse - see ObstacleClass.</summary>
        public ObstacleClass Class;
    }

    /// <summary>
    /// Coarse obstacle classification.
    ///
    /// HONESTY NOTE: in the simulator these labels are read from the source GameObject's layer and
    /// tag, i.e. the simulator already knows the answer. A real system would have to infer this
    /// from sensor data with a detector network, and would get it wrong sometimes. The class
    /// labels are therefore presented in the UI as coming from the simulator's ground truth, and
    /// the planner is written NOT to depend on them for safety decisions - it uses geometry and
    /// motion only. That way the avoidance logic remains valid when classification is imperfect.
    /// </summary>
    public enum ObstacleClass
    {
        Unknown = 0,
        Building = 1,
        Terrain = 2,
        Vegetation = 3,
        Pole = 4,
        Wire = 5,
        GroundVehicle = 6,
        Aircraft = 7,
        Bird = 8,
        NoFlyZone = 9
    }

    /// <summary>
    /// Threat level assigned to an obstacle by the threat analyser. Drives the AI decision panel.
    /// </summary>
    public enum ThreatLevel
    {
        /// <summary>Detected, no intersection with the planned corridor.</summary>
        None = 0,

        /// <summary>Near the corridor. Worth watching, no action.</summary>
        Low = 1,

        /// <summary>Intersects the corridor at a comfortable time horizon. Plan an avoidance.</summary>
        Medium = 2,

        /// <summary>Intersects soon. Execute avoidance now.</summary>
        High = 3,

        /// <summary>Collision imminent. Reflexive braking manoeuvre, bypass the planner.</summary>
        Critical = 4
    }

    /// <summary>
    /// The full telemetry snapshot presented to the ground station. One struct per frame keeps the
    /// UI decoupled from the internals of every subsystem: panels read this and nothing else.
    /// </summary>
    public struct TelemetrySnapshot
    {
        // Attitude, degrees
        public float RollDeg;
        public float PitchDeg;
        public float YawDeg;
        public float HeadingDeg;

        // Position and motion
        public float AltitudeAglM;       // above ground level
        public float AltitudeMslM;       // above the origin datum
        public float GroundSpeedMps;
        public float VerticalSpeedMps;
        public Vector3 VelocityWorld;
        public double Latitude;
        public double Longitude;

        // Power
        public float BatteryPercent;
        public float BatteryVoltage;
        public float BatteryCurrentA;
        public float BatteryConsumedMah;
        public float EstimatedFlightTimeRemainingS;

        // Propulsion
        public float Motor1Rpm;
        public float Motor2Rpm;
        public float Motor3Rpm;
        public float Motor4Rpm;
        public float ThrottlePercent;

        // Navigation
        public bool GpsEnabled;
        public int SatelliteCount;
        public float Hdop;
        public string LocalizationSource;
        public float LocalizationConfidence;

        // Mission
        public float MissionProgressPercent;
        public float DistanceToTargetM;
        public float DistanceRemainingM;
        public float EtaSeconds;
        public string FlightModeName;
        public string FlightStateName;

        public bool IsArmed;
        public double Timestamp;
    }
}
